server:
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehiclepasser_driver?createDatabaseIfNotExist=true
    password: 1234
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update