server:
  port: 0
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehiclepasser_driver?createDatabaseIfNotExist=true
    password: 1234
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#  instance:
#    instance-id: ${spring.application.name}-${random.int}
#    hostname: localhost


