spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/vehiclepasser_transaction?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
