server:
  error:
    include-message: always
spring:
  mail:
    host: smtp.gmail.com
    password: hellosrilanka
    username: chazooltopup@gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000

# SSL, post 465
#spring.mail.properties.mail.smtp.socketFactory.port = 465
#spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory




  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/vehiclepasser_payment?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update





