server:
  port: 9191
spring:
  datasource:
    # url: jdbc:mysql://auth-db:3306/vehiclepasser_auth?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/vehiclepasser_auth?createDatabaseIfNotExist=true
    #?autoReconnect=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost











